# fly.toml app configuration file generated for community-activity-platform-xum-bw on 2025-08-17T03:09:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'community-activity-platform-xum-bw'
primary_region = 'lax'

[build]

[env]
  MYSQL_HOST = "localhost"  # 使用数据库实例的主机名（可以是内部或外部 URL，具体取决于您的设置）
  MYSQL_PORT = "3306"      # 默认 MySQL 端口
  MYSQL_DATABASE = "community_activity_platform"  # 数据库名称
  MYSQL_USER = "root"      # 数据库用户名
  MYSQL_PASSWORD = "123456"  # 数据库密码
  DATABASE_URL = "mysql://root:123456@localhost:3306/community_activity_platform"  # 连接 URL，改为符合您的设置
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
