# fly.toml app configuration file generated for community-activity-platform-xum-bw on 2025-08-17T03:09:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'community-activity-platform-xum-bw'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
